spring:
  application:
    name: MAY 2024 SPRING DEMO
  profiles:
    active: store1
  datasource:
    url: "jdbc:postgresql://localhost:5432/XXX"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: ${mongodb-uri}
      database: "online-store"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-sender}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-d8rm3bg4cwywnjin.eu.auth0.com/
  cloud:
    stream:
      bindings:
        product-deleted-out-0:
          destination: product-deleted-events
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092