spring:
  application:
    name: MAY 2024 SPRING DEMO
  profiles:
    active: store1
  datasource:
    url: "jdbc:postgresql://localhost:5432/XXX"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true